### ISSUE TITLE
Canvas bounding-box

### ISSUE THREAD

**Issue by fabiopedrosa** [vitaliymaz/vscode-svg-previewer#21]
Could we have some dashed box to see where the SVG bouding-box is?

**Comment by vitaliymaz** [comment]
@fabiopedrosa, thank you for the feedback. I can see Webstorm does that, so looks useful. Proposing to make this disabled by default and add a setting to switch on.

**Comment by vitaliymaz** [comment]
Implemented in v0.3.2. Could be switched on by the setting option.

**Comment by vincerubinetti** [comment]
As implemented, it doesn't show the true viewBox. Only either the horizontal or vertical boundaries are accurate, depending on the aspect ratio of your preview window

![ezgif-3-e64b7163ee3f](https://user-images.githubusercontent.com/8326331/107102515-adbf4880-67e8-11eb-8ede-01082b59e090.gif)

Probably something to do with how browsers fit SVGs to their parent containers by default.

Related lines? :

https://github.com/vitaliymaz/vscode-svg-previewer/blob/c305d7b136336076e13dc49b4df8e69b020422dd/media/preview.css#L65

https://github.com/vitaliymaz/vscode-svg-previewer/blob/c305d7b136336076e13dc49b4df8e69b020422dd/media/preview.css#L3

https://github.com/vitaliymaz/vscode-svg-previewer/blob/c305d7b136336076e13dc49b4df8e69b020422dd/preview-src/components/Preview.tsx#L29

**Comment by deluksic** [comment]
> As implemented, it doesn't show the true viewBox. Only either the horizontal or vertical boundaries are accurate, depending on the aspect ratio of your preview window

Still seeing this. Any chance we could get this fixed?
